version: "3"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/data/db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=epworld

volumes:
  pg-data: